//Jobs Types
export const GET_ALL_JOBS = 'GET_ALL_JOBS'
export const GET_ONE_JOB = 'GET_ONE_JOB'
export const EDIT_JOB = 'EDIT_JOB'
export const DELETE_JOB = 'DELETE_JOB'
export const ADD_JOB = 'ADD_JOB'
export const GET_COMPANY_JOBS = 'GET_COMPANY_JOBS'

//Error Types
export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

//AUTH TYPES
export const USER_LOADED = 'USER_LOADED'
export const USER_LOADING = 'USER_LOADING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const GET_ALL_USERS = 'GET_ALL_USERS'
export const BLOCK_USER = 'BLOCK_USER'


//EMPLOYEE TYPES
export const GET_ALL_EMPLOYEES = 'GET_ALL_EMPLOYEE'
export const GET_ONE_EMPLOYEE = 'GET_ONE_EMPLOYEE'
export const EDIT_EMPLOYEE = 'EDIT_EMPLOYEE'
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE'
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE'
export const EMPLOYEE_LOADED = 'EMPLOYEE_LOADED'
export const EMPLOYEE_LOADING = 'EMPLOYEE_LOADING'
export const CLEAR_CURRENT_EMPLOYEE = 'CLEAR_CURRENT_EMPLOYEE'
//COMPANY TYPES
export const GET_ALL_COMPANIES = 'GET_ALL_COMPANIES'
export const GET_ONE_COMPANY = 'GET_ONE_COMPANY'
export const EDIT_COMPANY = 'EDIT_COMPANY'
export const DELETE_COMPANY = 'DELETE_COMPANY'
export const ADD_COMPANY = 'ADD_COMPANY'
export const COMPANY_LOADING = 'COMPANY_LOADING'
export const COMPANY_LOADED = 'COMPANY_LOADED'
export const COMPANY_EDITED = 'COMPANY_EDITED'
export const CLEAR_CURRENT_COMPANY = 'CLEAR_CURRENT_COMPANY'